$(document).ready(function () {
    $("#edate").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate").datepicker("option", "yearRange", '2018:2019');
    $('#edate').datepicker('option', 'minDate', '01/06/2018');
    $('#edate').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate1").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate1").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate1").datepicker("option", "yearRange", '2018:2019');
    $('#edate1').datepicker('option', 'minDate', '01/06/2018');
    $('#edate1').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate2").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate2").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate2").datepicker("option", "yearRange", '2018:2019');
    $('#edate2').datepicker('option', 'minDate', '01/06/2018');
    $('#edate2').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate3").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate3").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate3").datepicker("option", "yearRange", '2018:2019');
    $('#edate3').datepicker('option', 'minDate', '01/06/2018');
    $('#edate3').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate4").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate4").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate4").datepicker("option", "yearRange", '2018:2019');
    $('#edate4').datepicker('option', 'minDate', '01/06/2018');
    $('#edate4').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate5").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate5").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate5").datepicker("option", "yearRange", '2018:2019');
    $('#edate5').datepicker('option', 'minDate', '01/06/2018');
    $('#edate5').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate11").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate11").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate11").datepicker("option", "yearRange", '2018:2019');
    $('#edate11').datepicker('option', 'minDate', '01/06/2018');
    $('#edate11').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate12").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate12").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate12").datepicker("option", "yearRange", '2018:2019');
    $('#edate12').datepicker('option', 'minDate', '01/06/2018');
    $('#edate12').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate13").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate13").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate13").datepicker("option", "yearRange", '2018:2019');
    $('#edate13').datepicker('option', 'minDate', '01/06/2018');
    $('#edate13').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate14").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate14").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate14").datepicker("option", "yearRange", '2018:2019');
    $('#edate14').datepicker('option', 'minDate', '01/06/2018');
    $('#edate14').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate15").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate15").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate15").datepicker("option", "yearRange", '2018:2019');
    $('#edate15').datepicker('option', 'minDate', '01/06/2018');
    $('#edate15').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate16").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate16").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate16").datepicker("option", "yearRange", '2018:2019');
    $('#edate16').datepicker('option', 'minDate', '01/06/2018');
    $('#edate16').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate17").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate17").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate17").datepicker("option", "yearRange", '2018:2019');
    $('#edate17').datepicker('option', 'minDate', '01/06/2018');
    $('#edate17').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate18").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate18").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate18").datepicker("option", "yearRange", '2018:2019');
    $('#edate18').datepicker('option', 'minDate', '01/06/2018');
    $('#edate18').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate19").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate19").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate19").datepicker("option", "yearRange", '2018:2019');
    $('#edate19').datepicker('option', 'minDate', '01/06/2018');
    $('#edate19').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate20").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate20").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate20").datepicker("option", "yearRange", '2018:2019');
    $('#edate20').datepicker('option', 'minDate', '01/06/2018');
    $('#edate20').datepicker('option', 'maxDate', '31/05/2019');

    $("#edate21").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate21").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate21").datepicker("option", "yearRange", '2018:2019');
    $('#edate21').datepicker('option', 'minDate', '01/06/2018');
    $('#edate21').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate22").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate22").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate22").datepicker("option", "yearRange", '2018:2019');
    $('#edate22').datepicker('option', 'minDate', '01/06/2018');
    $('#edate22').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate23").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate23").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate23").datepicker("option", "yearRange", '2018:2019');
    $('#edate23').datepicker('option', 'minDate', '01/06/2018');
    $('#edate23').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate24").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate24").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate24").datepicker("option", "yearRange", '2018:2019');
    $('#edate24').datepicker('option', 'minDate', '01/06/2018');
    $('#edate24').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate25").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate25").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate25").datepicker("option", "yearRange", '2018:2019');
    $('#edate25').datepicker('option', 'minDate', '01/06/2018');
    $('#edate25').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate26").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate26").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate26").datepicker("option", "yearRange", '2018:2019');
    $('#edate26').datepicker('option', 'minDate', '01/06/2018');
    $('#edate26').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate27").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate27").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate27").datepicker("option", "yearRange", '2018:2019');
    $('#edate27').datepicker('option', 'minDate', '01/06/2018');
    $('#edate27').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate28").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate28").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate28").datepicker("option", "yearRange", '2018:2019');
    $('#edate28').datepicker('option', 'minDate', '01/06/2018');
    $('#edate28').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate29").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate29").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate29").datepicker("option", "yearRange", '2018:2019');
    $('#edate29').datepicker('option', 'minDate', '01/06/2018');
    $('#edate29').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate30").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate30").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate30").datepicker("option", "yearRange", '2018:2019');
    $('#edate30').datepicker('option', 'minDate', '01/06/2018');
    $('#edate30').datepicker('option', 'maxDate', '31/05/2019');

    $("#edate31").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate31").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate31").datepicker("option", "yearRange", '2018:2019');
    $('#edate31').datepicker('option', 'minDate', '01/06/2018');
    $('#edate31').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate32").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate32").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate32").datepicker("option", "yearRange", '2018:2019');
    $('#edate32').datepicker('option', 'minDate', '01/06/2018');
    $('#edate32').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate33").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate33").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate33").datepicker("option", "yearRange", '2018:2019');
    $('#edate33').datepicker('option', 'minDate', '01/06/2018');
    $('#edate33').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate34").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate34").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate34").datepicker("option", "yearRange", '2018:2019');
    $('#edate34').datepicker('option', 'minDate', '01/06/2018');
    $('#edate34').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate35").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate35").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate35").datepicker("option", "yearRange", '2018:2019');
    $('#edate35').datepicker('option', 'minDate', '01/06/2018');
    $('#edate35').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate36").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate36").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate36").datepicker("option", "yearRange", '2018:2019');
    $('#edate36').datepicker('option', 'minDate', '01/06/2018');
    $('#edate36').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate37").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate37").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate37").datepicker("option", "yearRange", '2018:2019');
    $('#edate37').datepicker('option', 'minDate', '01/06/2018');
    $('#edate37').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate38").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate38").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate38").datepicker("option", "yearRange", '2018:2019');
    $('#edate38').datepicker('option', 'minDate', '01/06/2018');
    $('#edate38').datepicker('option', 'maxDate', '31/05/2019');
    // Aux Event
    $("#edateAux").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edateAux").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edateAux").datepicker("option", "yearRange", '2018:2019');
    $('#edateAux').datepicker('option', 'minDate', '01/06/2018');
    $('#edateAux').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate41").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate41").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate41").datepicker("option", "yearRange", '2018:2019');
    $('#edate41').datepicker('option', 'minDate', '01/06/2018');
    $('#edate41').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate42").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate42").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate42").datepicker("option", "yearRange", '2018:2019');
    $('#edate42').datepicker('option', 'minDate', '01/06/2018');
    $('#edate42').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate43").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate43").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate43").datepicker("option", "yearRange", '2018:2019');
    $('#edate43').datepicker('option', 'minDate', '01/06/2018');
    $('#edate43').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate44").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate44").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate44").datepicker("option", "yearRange", '2018:2019');
    $('#edate44').datepicker('option', 'minDate', '01/06/2018');
    $('#edate44').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate45").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate45").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate45").datepicker("option", "yearRange", '2018:2019');
    $('#edate45').datepicker('option', 'minDate', '01/06/2018');
    $('#edate45').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate46").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate46").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate46").datepicker("option", "yearRange", '2018:2019');
    $('#edate46').datepicker('option', 'minDate', '01/06/2018');
    $('#edate46').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate47").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate47").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate47").datepicker("option", "yearRange", '2018:2019');
    $('#edate47').datepicker('option', 'minDate', '01/06/2018');
    $('#edate47').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate48").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate48").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate48").datepicker("option", "yearRange", '2018:2019');
    $('#edate48').datepicker('option', 'minDate', '01/06/2018');
    $('#edate48').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate49").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate49").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate49").datepicker("option", "yearRange", '2018:2019');
    $('#edate49').datepicker('option', 'minDate', '01/06/2018');
    $('#edate49').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate50").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate50").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate50").datepicker("option", "yearRange", '2018:2019');
    $('#edate50').datepicker('option', 'minDate', '01/06/2018');
    $('#edate50').datepicker('option', 'maxDate', '31/05/2019');
    
    // Fairs and Festivals
    $("#edateff").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edateff").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edateff").datepicker("option", "yearRange", '2018:2019');
    $('#edateff').datepicker('option', 'minDate', '01/06/2018');
    $('#edateff').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate51").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate51").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate51").datepicker("option", "yearRange", '2018:2019');
    $('#edate51').datepicker('option', 'minDate', '01/06/2018');
    $('#edate51').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate52").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate52").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate52").datepicker("option", "yearRange", '2018:2019');
    $('#edate52').datepicker('option', 'minDate', '01/06/2018');
    $('#edate52').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate53").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate53").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate53").datepicker("option", "yearRange", '2018:2019');
    $('#edate53').datepicker('option', 'minDate', '01/06/2018');
    $('#edate53').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate54").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate54").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate54").datepicker("option", "yearRange", '2018:2019');
    $('#edate54').datepicker('option', 'minDate', '01/06/2018');
    $('#edate54').datepicker('option', 'maxDate', '31/05/2019');
    $("#edate55").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edate55").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edate55").datepicker("option", "yearRange", '2018:2019');
    $('#edate55').datepicker('option', 'minDate', '01/06/2018');
    $('#edate55').datepicker('option', 'maxDate', '31/05/2019');
    
    $("#edatecalendar").datepicker({altFormat: 'MM/DD/YYYY', autosize: true, changeMonth: true, changeYear: true});
    $("#edatecalendar").datepicker("option", "dateFormat", 'dd/mm/yy');
    $("#edatecalendar").datepicker("option", "yearRange", '2017:2019');
    $('#edatecalendar').datepicker('option', 'minDate', '01/06/2017');
    $('#edatecalendar').datepicker('option', 'maxDate', '31/05/2019');
});